# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ihelp32.ru
title: brobrohelp
email: brobrohelp@gmail.com
author: 'Petr Stepchenko <nitrinodev@gmail.com>'
description: 'Ремонт и обслуживание техники Apple: iPhone, iPad, MacBook, iMac'
copyright: 'Copyright &copy; 2017 brobrohelp.ru. All Rights Reserved.'
credits: 'Информация опубликованная на сайте не является публичной офертой, определяемой положениями Статьи 437 ГК РФ.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: vk
    url: https://vk.com/brobrohelp
  - title: instagram
    url: https://www.instagram.com/brobrohelp/
  - title: Telegram
    url: https://t.me/brobrohelp
