# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ihelp32.ru
title: iHelp32service
email: your-email@domain.com
author: Petr Stepchenko
description: > # "Ремонт любого уровня сложности техники Apple: iPhone, iPad, MacBook, iMac.
  Услуги замена ваших iPhone, iPad и iPod на новые устройства.
  Гарантия на все услуги.
copyright: 'Copyright &copy; 2017 iHelp32.ru. All Rights Reserved.'
credits: 'Информация опубликованная на сайте не является публичной офертой, определяемой положениями Статьи 437 ГК РФ.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: vk
    url: https://vk.com/ihelp32
  - title: instagram
    url: https://www.instagram.com/Ihelp32service/
