# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ihelp32.ru
title: iHelp32 service
email: your-email@domain.com
author: Petr Stepchenko
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2017 iHelp32.ru. All Rights Reserved.'
credits: 'Информация опубликованная на сайте не является публичной офертой, определяемой положениями Статьи 437 ГК РФ.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: vk
    url: https://vk.com/ihelp32
  - title: instagram
    url: https://www.instagram.com/Ihelp32service/
